import type { Trip } from "./types";

export function createEmptyTrip(overrides: Partial<Trip> = {}): Trip {
  // Local calendar date (YYYY-MM-DD) — the operator's day. `toISOString()` is
  // UTC and rolls a day early for timezones ahead of UTC, which would put a
  // freshly-created trip on a different day than the rest of the app
  // (Orders' localToday(), the server's CURRENT_DATE).
  const d = new Date();
  const now = d.toISOString();
  const tripDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate()
  ).padStart(2, "0")}`;
  return {
    id: 0,
    tripNo: "",
    tripDate,
    legCount: 1,
    activeLegIndex: 1,
    legs: [],
    startTime: "",
    vehicleId: 0,
    vehicleNo: "",
    driverId: 0,
    driverName: "",
    supervisorId: 0,
    supervisorName: "",
    helpers: [],
    loaders: [],
    openingMeter: null,
    advanceAmount: null,
    startStepSubmitted: false,
    sourceFarmId: 0,
    sourceFarm: "",
    birdTypeId: 0,
    birdType: "",
    reachedTime: "",
    destMeter: 0,
    pickupTolls: 0,
    farmStepSubmitted: false,
    farmAddress: "",
    avgBirdWeight: 0,
    farmGpsLat: null,
    farmGpsLon: null,
    farmGpsAccuracy: null,
    farmGpsTime: null,
    dcWeight: 0,
    totalBirds: 0,
    boxes: 0,
    boxDetails: [],
    avgWeight: 0,
    pickupLoadTime: "",
    pickupStepSubmitted: false,
    deliveries: [],
    deliveryStepSubmitted: false,
    closingMeter: 0,
    endTime: "",
    deliveryTolls: 0,
    endStepSubmitted: false,
    expensesStepSubmitted: false,
    expensesStepSubmittedAt: "",
    dieselEntries: [],
    mileageKmL: null,
    totalKm: 0,
    totalShops: 0,
    totalWeight: 0,
    totalDeliveredWeight: 0,
    totalBirdsDelivered: 0,
    totalMortality: 0,
    totalMortalityCount: 0,
    totalMortalityWeight: 0,
    weightLoss: 0,
    survivalRate: 0,
    lastShop: "",
    status: "Draft",
    fuel: 0,
    expense: 0,
    remarks: "",
    rateCompleted: false,
    createdAt: now,
    updatedAt: now,
    boxNo: 0,
    birds: 0,
    weight: 0,
    ...overrides,
  };
}
