// Fictional, browser-test-only records. Never supplied to the live ERP API.
export const DEPARTMENTS = [
  'Accountant',
  'Collection',
  'Driver',
  'Helper',
  'Loader',
  'Office Staff',
  'Operations',
  'Other',
  'Sales',
  'Supervisor',
];
export type TestRecord = { id: number; [key: string]: unknown };
export const fixtures: Record<string, TestRecord[]> = {
  shops: Array.from({ length: 35 }, (_, index) => ({
    id: index + 1,
    shopNo: index + 1,
    shopNumber: `TEST-${index + 1}`,
    shopName: `Sample Shop ${String(index + 1).padStart(2, '0')}`,
    ownerName: `Sample Owner ${index + 1}`,
    phoneNumber: String(9000000000 + index),
    secondaryPhoneNumber: '',
    email: '',
    city: ['Hyderabad', 'Guntur', 'Warangal'][index % 3],
    address: 'Sample address',
    latitude: 0,
    longitude: 0,
    paperRate: (index % 30) + 1,
    associationType: 'Ass Vij',
    openingBalance: 1500,
    currentBalance: 1500,
    status: index % 5 ? 'Active' : 'Inactive',
  })),
  farms: Array.from({ length: 12 }, (_, index) => ({
    id: index + 1,
    farmNo: index + 1,
    farmName: `Sample Farm ${index + 1}`,
    ownerName: `Sample Farmer ${index + 1}`,
    supervisorName: `Sample Supervisor ${index + 1}`,
    phoneNumber: String(9100000000 + index),
    village: 'Sample Village',
    address: 'Sample farm address',
    capacity: 2500,
    status: 'Active',
  })),
  vehicles: Array.from({ length: 12 }, (_, index) => ({
    id: index + 1,
    vehicleNo: index + 1,
    vehicleNumber: `TEST-${String(index + 1).padStart(4, '0')}`,
    vehicleType: 'LCV',
    noOfBoxes: 100,
    birdCapacity: 2000,
    capacityKg: 3500,
    engineNumber: `TEST-ENGINE-${index + 1}`,
    chassisNumber: `TEST-CHASSIS-${index + 1}`,
    fastagBank: 'Sample Bank',
    purchaseDate: '2025-04-01',
    purchaseAmount: 800000,
    emiDay: 15,
    totalEMIs: 36,
    rcDate: '2025-04-03',
    trackingId: 'TEST-GPS',
    status: 'Active',
  })),
  employees: Array.from({ length: 20 }, (_, index) => ({
    id: index + 1,
    employeeNo: index + 1,
    employeeName: `Sample Employee ${String(index + 1).padStart(2, '0')}`,
    department: DEPARTMENTS[index % DEPARTMENTS.length],
    role: 'Sample role',
    phoneNumber: String(9200000000 + index),
    email: '',
    address: 'Sample employee address',
    joiningDate: '2025-04-01',
    salary: 20000 + index * 100,
    licenseNumber: 'TEST-LICENSE',
    status: 'Active',
  })),
  banks: Array.from({ length: 12 }, (_, index) => ({
    id: index + 1,
    bankNo: index + 1,
    bankName: `Sample Bank ${index + 1}`,
    branch: 'Sample Branch',
    accountNumber: `TESTACC${index + 1}`,
    ifscCode: 'TEST0000001',
    upiId: 'sample@test',
    status: 'Active',
  })),
  'bird-types': Array.from({ length: 12 }, (_, index) => ({
    id: index + 1,
    birdTypeNo: index + 1,
    birdType: `Sample Bird Type ${index + 1}`,
    averageWeight: 1.5,
    description: 'Sample description',
    status: 'Active',
  })),
};
