/**
 * Compatibility facade for existing Desktop Trip imports.
 * Shared calculations and validation are authoritative for Desktop + Mobile.
 * Trip numbers are generated by the PostgreSQL backend — the legacy
 * browser/localStorage numbering helpers were removed (Gate 0).
 */
export {
  calculateAvgWeight,
  calculateTripKPIs,
  calculateTotals,
  calculatePickupTotals,
  calculateDeliveryMetrics,
  applyDeliveryMetrics,
  calculateDeliveryDisplayTotals,
  calculateKM,
  calculateTripDistances,
  sumFlattenedDieselLitres,
} from "../../../../shared/trip/calculations";
export {
  validateStartStep,
  validateFarmStep,
  validatePickupStep,
  validateDeliveriesStep,
  validateEndStep,
  validateFinalTrip,
  validateTrip,
} from "../../../../shared/trip/validation";

export function canEditTrip(createdAt: string): boolean {
  const differenceDays = Math.floor(
    (Date.now() - new Date(createdAt).getTime()) / (1000 * 60 * 60 * 24)
  );
  return differenceDays <= 10;
}

export function canDeleteTrip(createdAt: string): boolean {
  return canEditTrip(createdAt);
}

export function isTripCompleted(status: "Pending" | "Completed"): boolean {
  return status === "Completed";
}

export function isTripPending(status: "Pending" | "Completed"): boolean {
  return status === "Pending";
}
